export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const AUTHENTICATE_USER_PENDING = "AUTHENTICATE_USER_PENDING";
export const AUTHENTICATE_USER_SUCCED = "AUTHENTICATE_USER_SUCCED";
export const AUTHENTICATE_USER_REJECTED = "AUTHENTICATE_USER_REJECTED";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_PENDING = "UPDATE_USER_PENDING";
export const UPDATE_USER_SUCCED = "UPDATE_USER_SUCCED";
export const UPDATE_USER_REJECTED = "UPDATE_USER_REJECTED";

export const CLEAR_VALUES = "CLEAR_VALUES";
export const CREATE_JOB_PENDING = "CREATE_JOB_PENDING";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";

export const GET_JOBS_PENDING = "GET_JOBS_BEGIN";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const GET_JOBS_ERROR = "GET_JOBS_ERROR";

export const SET_EDIT_JOB = "SET_EDIT_JOB";
export const DELETE_JOB_PENDING = "DELETE_JOB_PENDING";
export const EDIT_JOB_PENDING = "EDIT_JOB_PENDING";
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_ERROR = "EDIT_JOB_ERROR";

export const SHOW_STATS_PENDING = "SHOW_STATS_PENDING";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const CHANGE_PAGE = "CHANGE_PAGE";

export const PAYMENT_PENDING = "PAYMENT_PENDING";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";

export const CLEAR_EMAIL_VALUES = "CLEAR_EMAIL_VALUES";
export const SEND_EMAIL_PENDING = "SEND_EMAIL_BEGIN";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_ERROR = "SEND_EMAIL_ERROR";

export const GOOGLE_SIGN_IN = "GOOGLE_SIGN_IN";

export const RESET_PASSWORD_PENDING = "RESET_PASSWORD_PENDING";
export const RESET_PASSWORD_SUCCED = "RESET_PASSWORD_SUCCED";
export const RESET_PASSWORD_REJECTED = "RESET_PASSWORD_REJECTED";
