export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const AUTHENTICATE_USER_PENDING = "AUTHENTICATE_USER_PENDING";
export const AUTHENTICATE_USER_SUCCED = "AUTHENTICATE_USER_SUCCED";
export const AUTHENTICATE_USER_REJECTED = "AUTHENTICATE_USER_REJECTED";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_PENDING = "UPDATE_USER_PENDING";
export const UPDATE_USER_SUCCED = "UPDATE_USER_SUCCED";
export const UPDATE_USER_REJECTED = "UPDATE_USER_REJECTED";

export const CLEAR_VALUES = "CLEAR_VALUES";
export const CREATE_JOB_PENDING = "CREATE_JOB_PENDING";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";
